fieldLayouts:
  8903b8f5-4f50-4c45-8791-fe7c336e7e0f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef5013ca-7d40-47a8-aedd-aa1f622f31b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ffdc79ed-f1d9-41e3-a305-6e0a0a368e63 # Header-Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ae71dfd-6d17-4fed-bff9-6cfbdc43ba1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b295ea57-abae-4faa-be54-1c7e86956ceb # Inhalt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a0ed7e6-6c86-4dee-80e8-766f6b9a6595
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 37eded68-691f-4151-b61b-fe00f93f8d15
        userCondition: null
handle: hotellerie
hasTitleField: false
name: Hotellerie
section: 2e17648f-09e8-4b43-88a1-92b246925e4d # Hotellerie
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
