defaultPlacement: end
handle: navigation
instructions: null
maxNodes: null
name: Navigation
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  putyourlightson\campaign\elements\CampaignElement:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: none
siteSettings:
  8f7c0986-6e59-416f-a40c-3cafdb4e5953: # $SYS_NAME
    enabled: true
sortOrder: 1
structure:
  maxLevels: null
  uid: 6f6469dc-7bd6-4748-999b-8f26be049889
