fieldLayouts:
  e48fec04-1f64-46fb-b8b0-fd8b09b1bd95:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4e3dd870-7448-44d5-b021-b9c43ebd85b8
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 44d9375a-2acd-41c6-9e26-90f776adfeb9
        userCondition: null
fs: interneDateien
handle: interneDateien
name: 'Interne Dateien'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
