columnSuffix: null
contentColumnType: string
fieldGroup: fea50c4b-4607-4f94-ad62-428efbe1d137 # Aktivitäten
handle: form
instructions: null
name: Formular
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
