columnSuffix: afxulwfd
contentColumnType: text
fieldGroup: cccc276f-76f1-40ae-a964-281e078791fe # Team
handle: lastname
instructions: null
name: Nachname
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
