columnSuffix: null
contentColumnType: string
fieldGroup: a79920c0-801d-495a-a41f-36add74f5319 # News&Ratgeber
handle: mainImage
instructions: "Optimalerweise ein Bild im Querformat. \r\nWird als Beitrags-Bild auf Übersicht verwendet."
name: Titelbild
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:ed7cb5c2-d98c-48fb-b033-83aecf9c869b' # Object-Storage
  defaultUploadLocationSubpath: beitraege/
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ed7cb5c2-d98c-48fb-b033-83aecf9c869b' # Object-Storage
  restrictedLocationSubpath: null
  selectionLabel: 'Bild hinzufügen'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
