columnSuffix: qrabohhs
contentColumnType: string
fieldGroup: b7747b1c-b7d1-4853-aecf-19b134ac11ae # Neo
handle: style
instructions: null
name: Anordnung
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Untereinander
        -
          - value
          - list
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Nebeneinander
        -
          - value
          - inline
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
