columnSuffix: hcdpdgai
contentColumnType: text
fieldGroup: b7747b1c-b7d1-4853-aecf-19b134ac11ae # Neo
handle: textMehrzeilig
instructions: null
name: Text
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
