columnSuffix: null
contentColumnType: string
fieldGroup: a79920c0-801d-495a-a41f-36add74f5319 # News&Ratgeber
handle: thema
instructions: null
name: Thema
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: 'Thema auswählen'
  showSiteMenu: false
  source: 'group:4dbbd3a1-c226-45dc-a0fc-803c378a3a9e'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
