defaultPlacement: end
enableVersioning: true
handle: sophieGuyer
name: 'Sophie Guyer'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8f7c0986-6e59-416f-a40c-3cafdb4e5953: # $SYS_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages/index
    uriFormat: 'sophie-guyer/{slug}'
structure:
  maxLevels: 1
  uid: 7380349f-85f1-46c8-a82e-2bbf66d133f3
type: structure
